// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq6dseQA_vpFB1P6Uj50xgEY0qiqYOeQ',
    appId: '1:656248853849:web:c5ea420bca173a88c0e848',
    messagingSenderId: '656248853849',
    projectId: 'trust-track',
    authDomain: 'trust-track.firebaseapp.com',
    storageBucket: 'trust-track.firebasestorage.app',
    measurementId: 'G-T10XXPRWNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4sm8Uc6_67MQP2sIghgkBiAa2Izhweik',
    appId: '1:656248853849:android:9ec5babd65a2f391c0e848',
    messagingSenderId: '656248853849',
    projectId: 'trust-track',
    storageBucket: 'trust-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceISnuqnco1Ea1Sm-nYmBvAE__GF7g70',
    appId: '1:656248853849:ios:2e83adddecd90389c0e848',
    messagingSenderId: '656248853849',
    projectId: 'trust-track',
    storageBucket: 'trust-track.firebasestorage.app',
    iosBundleId: 'com.example.trustTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceISnuqnco1Ea1Sm-nYmBvAE__GF7g70',
    appId: '1:656248853849:ios:2e83adddecd90389c0e848',
    messagingSenderId: '656248853849',
    projectId: 'trust-track',
    storageBucket: 'trust-track.firebasestorage.app',
    iosBundleId: 'com.example.trustTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARq6dseQA_vpFB1P6Uj50xgEY0qiqYOeQ',
    appId: '1:656248853849:web:7e1638ddc00ee5a2c0e848',
    messagingSenderId: '656248853849',
    projectId: 'trust-track',
    authDomain: 'trust-track.firebaseapp.com',
    storageBucket: 'trust-track.firebasestorage.app',
    measurementId: 'G-SW530YSPQW',
  );

}